[package]
name = "kumo"
description = "The Kiri Wayfire Shell"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "s"
strip = "debuginfo"
lto = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4", features = ["derive", "env"] }
color-eyre = "0.6"
dotenvy = { version = "0.15", features = ["clap"] }
lazy_static = "1.4"
once_cell = "1.19"
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"
tracing = { version = "0.1.40", features = ["log", "async-await"] }
tracing-subscriber = { version = "0.3", features = [
    "tracing",
    "chrono",
    "env-filter",
    "serde",
    "serde_json",
    "tracing-serde",
] }
gio = "0.18.4"
glib = { version = "0.18.5", features = ["v2_78"] }
gtk4-layer-shell = "0.2.0"
libhelium = { version = "0.1.0", features = ["gtk_v4_10", "v1_6"] }
chrono = { version = "0.4", features = ["serde"] }

[dependencies.gtk]
version = "0.7.0"
package = "gtk4"
features = ["v4_10", "blueprint"]



[workspace]
members = ["shizuku", "wayland-wf-shell"]
