[package]
name = "kumo"
description = "The Kiri Wayfire Shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4", features = ["derive", "env"] }
color-eyre = "0.6"
dotenvy = { version = "0.15", features = ["clap"] }
lazy_static = "1.4"
once_cell = "1.19"
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"
tracing = { version = "0.1.40", features = ["log", "async-await"] }
tracing-subscriber = { version = "0.3", features = [
    "tracing",
    "chrono",
    "env-filter",
    "serde",
    "serde_json",
    "tracing-serde",
] }


[workspace]
members = [ "shizuku","wayland-wf-shell"]
