[package]
name = "kumo"
description = "The Kiri Wayfire Shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive", "env"] }
color-eyre = "0.6.2"
dotenvy = { version = "0.15.7", features = ["clap"] }
lazy_static = "1.4.0"
once_cell = "1.19.0"
serde = { version = "1.0.196", features = ["serde_derive"] }
serde_json = "1.0.113"
tracing = { version = "0.1.40", features = ["log", "async-await"] }
tracing-subscriber = "0.3.18"
